In [106]:
import numpy as np

In [107]:
import pandas as pd

In [108]:
new_climatedata=pd.read_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/new_climate_analysis.csv")

In [109]:
new_climatedata_copy=new_climatedata.copy()

In [110]:
new_climatedata_copy['Date'] = new_climatedata_copy['MO'].map(str) + '/' + new_climatedata_copy['DY'].map(str) + '/' + new_climatedata_copy['YEAR'].map(str)
print (new_climatedata_copy)

      YEAR  MO  DY    T2M  PRECTOTCORR        Date
0     2000   1   1  14.27         0.00    1/1/2000
1     2000   1   2  17.54         0.01    1/2/2000
2     2000   1   3  12.62         0.00    1/3/2000
3     2000   1   4   3.95         0.00    1/4/2000
4     2000   1   5   4.19         0.00    1/5/2000
...    ...  ..  ..    ...          ...         ...
8031  2021  12  27  19.58         0.59  12/27/2021
8032  2021  12  28  19.93         0.91  12/28/2021
8033  2021  12  29  18.08         3.09  12/29/2021
8034  2021  12  30  15.46         0.00  12/30/2021
8035  2021  12  31  19.43         1.21  12/31/2021

[8036 rows x 6 columns]

In [111]:
new_climatedata_copy

      YEAR  MO  DY    T2M  PRECTOTCORR        Date
0     2000   1   1  14.27         0.00    1/1/2000
1     2000   1   2  17.54         0.01    1/2/2000
2     2000   1   3  12.62         0.00    1/3/2000
3     2000   1   4   3.95         0.00    1/4/2000
4     2000   1   5   4.19         0.00    1/5/2000
...    ...  ..  ..    ...          ...         ...
8031  2021  12  27  19.58         0.59  12/27/2021
8032  2021  12  28  19.93         0.91  12/28/2021
8033  2021  12  29  18.08         3.09  12/29/2021
8034  2021  12  30  15.46         0.00  12/30/2021
8035  2021  12  31  19.43         1.21  12/31/2021

[8036 rows x 6 columns]

In [112]:
print(type(new_climatedata_copy['Date']))

<class 'pandas.core.series.Series'>

In [113]:
new_climatedata_copy['Date']=pd.to_datetime(new_climatedata_copy['Date'])

In [114]:
new_climatedata_copy

      YEAR  MO  DY    T2M  PRECTOTCORR       Date
0     2000   1   1  14.27         0.00 2000-01-01
1     2000   1   2  17.54         0.01 2000-01-02
2     2000   1   3  12.62         0.00 2000-01-03
3     2000   1   4   3.95         0.00 2000-01-04
4     2000   1   5   4.19         0.00 2000-01-05
...    ...  ..  ..    ...          ...        ...
8031  2021  12  27  19.58         0.59 2021-12-27
8032  2021  12  28  19.93         0.91 2021-12-28
8033  2021  12  29  18.08         3.09 2021-12-29
8034  2021  12  30  15.46         0.00 2021-12-30
8035  2021  12  31  19.43         1.21 2021-12-31

[8036 rows x 6 columns]

In [115]:
twoBDAdata=pd.read_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/climate analysis/2bdadataforanalysis.csv")

In [116]:
twoBDAdata['Date']=pd.to_datetime(twoBDAdata['Date'])

In [117]:
twoBDAdata.head()

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,p.2,sur_refl_b01.2,sur_refl_b02.2,sur_refl_b03.2,sur_refl_b04.2,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong
0,2000-06-01,156.060606,1.073742e+09,-1737.454545,1934.121212,1049.515152,3904.969697,1.272331,2956.636364,3717.575758,...,0,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\..."
1,2000-06-09,164.030303,1.074687e+09,-1381.090909,1922.272727,1293.121212,4098.393939,1.502990,1488.757576,2277.818182,...,0,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\..."
2,2000-06-17,173.484848,1.073742e+09,7163.060606,1662.666667,4516.424242,4540.636364,2.022717,945.121212,1913.727273,...,0,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\..."
3,2000-06-25,177.000000,1.350312e+09,-1762.727273,1605.515152,4519.272727,982.636364,2.703099,960.060606,2698.757576,...,0,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\..."
4,2000-07-03,186.000000,1.090011e+09,-1521.181818,1786.515152,80.000000,2157.151515,2.881762,816.242424,2348.000000,...,0,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\..."

In [118]:
year_copy=twoBDAdata.copy()

In [119]:
year_copy['year'] = pd.DatetimeIndex(year_copy['Date']).year

In [120]:
year_copy

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b01.2,sur_refl_b02.2,sur_refl_b03.2,sur_refl_b04.2,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,year
0,2000-06-01,156.060606,1.073742e+09,-1737.454545,1934.121212,1049.515152,3904.969697,1.272331,2956.636364,3717.575758,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
1,2000-06-09,164.030303,1.074687e+09,-1381.090909,1922.272727,1293.121212,4098.393939,1.502990,1488.757576,2277.818182,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
2,2000-06-17,173.484848,1.073742e+09,7163.060606,1662.666667,4516.424242,4540.636364,2.022717,945.121212,1913.727273,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
3,2000-06-25,177.000000,1.350312e+09,-1762.727273,1605.515152,4519.272727,982.636364,2.703099,960.060606,2698.757576,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
4,2000-07-03,186.000000,1.090011e+09,-1521.181818,1786.515152,80.000000,2157.151515,2.881762,816.242424,2348.000000,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,2020-06-25,184.000000,1.073742e+09,-1277.000000,1954.515152,4065.818182,1163.636364,3.066000,606.454545,1853.424242,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020
923,2020-07-03,185.000000,1.073742e+09,14984.242420,1188.000000,88.000000,5614.000000,1.966876,749.303030,1477.727273,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020
924,2020-07-11,193.000000,1.074759e+09,-1153.212121,2153.515152,115.151515,2349.151515,3.929599,706.424242,2831.030303,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020
925,2020-07-19,201.484848,1.074759e+09,6822.121212,1865.181818,4734.666667,4527.151515,3.388338,764.969697,2647.939394,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020
926,2020-07-27,214.000000,1.073742e+09,15303.909090,2081.515152,4519.515152,1384.363636,2.695053,770.545455,2071.939394,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020

In [121]:
year_copy_group=year_copy.groupby(['year'])[['p'  ]].mean()

In [122]:
for_year_climate=new_climatedata_copy.copy()

In [123]:
for_year_climate['year']=pd.DatetimeIndex(for_year_climate['Date']).year

In [124]:
for_year_climate_group=for_year_climate.groupby(['year'])[['T2M','PRECTOTCORR'  ]].mean()

In [125]:
for_year_climate_group.head()

            T2M  PRECTOTCORR
year
2000  19.843388     2.404863
2001  18.976575     2.483014
2002  18.948767     2.396767
2003  19.245315     1.912795
2004  19.012923     3.445355

In [34]:
year_copy.head()

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b01.2,sur_refl_b02.2,sur_refl_b03.2,sur_refl_b04.2,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,year
0,2000-06-01,156.060606,1.073742e+09,-1737.454545,1934.121212,1049.515152,3904.969697,1.272331,2956.636364,3717.575758,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
1,2000-06-09,164.030303,1.074687e+09,-1381.090909,1922.272727,1293.121212,4098.393939,1.502990,1488.757576,2277.818182,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
2,2000-06-17,173.484848,1.073742e+09,7163.060606,1662.666667,4516.424242,4540.636364,2.022717,945.121212,1913.727273,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
3,2000-06-25,177.000000,1.350312e+09,-1762.727273,1605.515152,4519.272727,982.636364,2.703099,960.060606,2698.757576,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000
4,2000-07-03,186.000000,1.090011e+09,-1521.181818,1786.515152,80.000000,2157.151515,2.881762,816.242424,2348.000000,...,0,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000

In [35]:
df_Time_week = new_climatedata_copy
df_Time_week = df_Time_week.groupby(pd.Grouper(key='Date', freq='W')).agg({'T2M': 'mean','PRECTOTCORR': 'mean'	})

In [36]:
df_Time_week.head()

                  T2M  PRECTOTCORR
Date
2000-01-02  15.905000     0.005000
2000-01-09   8.455714     5.355714
2000-01-16  13.211429     0.017143
2000-01-23  13.655714     0.000000
2000-01-30   2.677143     1.858571

In [37]:
df_Time_week.groupby('Date').aggregate(['min', np.median, max])

                  T2M                       PRECTOTCORR
                  min     median        max         min    median       max
Date
2000-01-02  15.905000  15.905000  15.905000    0.005000  0.005000  0.005000
2000-01-09   8.455714   8.455714   8.455714    5.355714  5.355714  5.355714
2000-01-16  13.211429  13.211429  13.211429    0.017143  0.017143  0.017143
2000-01-23  13.655714  13.655714  13.655714    0.000000  0.000000  0.000000
2000-01-30   2.677143   2.677143   2.677143    1.858571  1.858571  1.858571
...               ...        ...        ...         ...       ...       ...
2021-12-05  16.894286  16.894286  16.894286    1.075714  1.075714  1.075714
2021-12-12  12.895714  12.895714  12.895714    0.425714  0.425714  0.425714
2021-12-19  15.814286  15.814286  15.814286    7.927143  7.927143  7.927143
2021-12-26  14.180000  14.180000  14.180000    0.361429  0.361429  0.361429
2022-01-02  18.496000  18.496000  18.496000    1.160000  1.160000  1.160000

[1149 rows x 6 columns]

In [38]:
df_Time_month=new_climatedata_copy

In [39]:
df_Time_Month = df_Time_month.groupby(pd.Grouper(key='Date', freq='M')).agg({'T2M': 'mean','PRECTOTCORR': 'mean'	})

In [40]:
df_Time_Month.head()

                  T2M  PRECTOTCORR
Date
2000-01-31   9.727742     1.645161
2000-02-29  13.910690     1.885862
2000-03-31  16.495484     1.792903
2000-04-30  19.520667     2.638333
2000-05-31  25.168387     2.804839

In [41]:
df_Time_Year =new_climatedata_copy

In [42]:
df_Time_Year = df_Time_month.groupby(pd.Grouper(key='Date', freq='Y')).agg({'T2M': 'mean','PRECTOTCORR': 'mean'	})

In [43]:
df_Time_Year.head()

                  T2M  PRECTOTCORR
Date
2000-12-31  19.843388     2.404863
2001-12-31  18.976575     2.483014
2002-12-31  18.948767     2.396767
2003-12-31  19.245315     1.912795
2004-12-31  19.012923     3.445355

In [44]:
df_Time_Year.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/yeear.csv")

In [45]:
df_Time_Month.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/month.csv")

In [46]:
df_Time_week.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/week.csv")

In [47]:
new_climatedata_copy.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/alldata.csv")

In [48]:
merged1 = pd.merge(twoBDAdata, df_Time_Month, left_on='Date', right_on='Date')

In [49]:
merged1.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/mergedbymonth.csv")

In [50]:
merged1.head()

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b02.2,sur_refl_b03.2,sur_refl_b04.2,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,T2M,PRECTOTCORR
0,2000-10-31,306.030303,1.073742e+09,-6360.818182,4787.575758,1168.757576,2209.848485,1.330526,1148.545455,1557.151515,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",20.251935,3.568710
1,2001-09-30,275.000000,1.073742e+09,-5569.727273,3798.515152,88.000000,1019.151515,2.942188,703.181818,2075.363636,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",23.934333,2.427000
2,2002-09-30,278.000000,1.073742e+09,-5589.757576,3931.030303,83.878788,1055.636364,2.276457,740.666667,1672.454545,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",26.043333,2.050000
3,2003-09-30,274.000000,1.073742e+09,-5214.666667,3864.515152,88.000000,2275.121212,2.989871,725.636364,2173.212121,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",23.958667,3.187000
4,2004-04-30,124.000000,1.073742e+09,-3146.242424,2258.515152,84.121212,1037.636364,2.354548,636.121212,1783.727273,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",18.840333,5.685333

In [51]:
merged2 = pd.merge(twoBDAdata, df_Time_week, left_on='Date', right_on='Date')

In [52]:
merged2.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/mergedbyweek.csv")

In [53]:
merged2.head()

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b02.2,sur_refl_b03.2,sur_refl_b04.2,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,T2M,PRECTOTCORR
0,2000-06-25,177.000000,1.350312e+09,-1762.727273,1605.515152,4519.272727,982.636364,2.703099,960.060606,2698.757576,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",27.918571,1.437143
1,2000-08-20,234.000000,1.073742e+09,-3818.636364,2533.030303,84.121212,2137.151515,2.389397,1104.848485,2655.484848,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",32.188571,0.192857
2,2000-10-15,292.000000,1.073742e+09,10852.030300,4162.515152,1043.878788,4465.848485,2.762074,797.484848,2135.727273,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",17.355714,1.971429
3,2000-12-10,349.969697,1.073742e+09,11197.818180,5566.090909,80.000000,2595.757576,1.468500,871.696970,1361.181818,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",8.371429,0.062857
4,2001-02-18,49.000000,1.073742e+09,12134.484850,4568.515152,120.969697,1575.878788,1.559962,850.909091,1428.454545,...,0,0,0,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",10.378571,5.317143

In [54]:
merged3 = pd.merge(year_copy_group,for_year_climate_group , left_on='year', right_on='year')

In [55]:
merged3

             p        T2M  PRECTOTCORR
year
2000  1.903395  19.843388     2.404863
2001  2.054036  18.976575     2.483014
2002  1.979776  18.948767     2.396767
2003  2.037902  19.245315     1.912795
2004  1.996618  19.012923     3.445355
2005  2.113199  19.502384     1.581123
2006  1.791401  20.362329     1.758329
2007  1.747671  18.255260     3.392795
2008  2.061013  19.332541     1.690219
2009  2.057332  19.277068     2.606575
2010  1.918029  18.809342     2.114740
2011  1.753483  20.708521     1.327918
2012  2.051470  20.395328     1.978743
2013  2.031663  19.029507     2.335808
2014  2.134060  18.667260     1.827945
2015  1.922514  19.472274     3.232493
2016  2.168768  19.587678     2.845464
2017  2.201143  20.189534     2.199041
2018  1.850561  19.489836     2.653151
2019  1.974003  19.281123     1.816055
2020  2.165068  19.895874     2.388333

In [56]:
merged3['Temp_bins']=pd.cut(merged3['T2M'], bins=3, labels=('low', 'middle', 'high'))

In [57]:
merged3['precip_bins']=pd.cut(merged3['PRECTOTCORR'], bins=3, labels=('low', 'middle', 'high'))

In [58]:
merged3

             p        T2M  PRECTOTCORR Temp_bins precip_bins
year
2000  1.903395  19.843388     2.404863    middle      middle
2001  2.054036  18.976575     2.483014       low      middle
2002  1.979776  18.948767     2.396767       low      middle
2003  2.037902  19.245315     1.912795    middle         low
2004  1.996618  19.012923     3.445355       low        high
2005  2.113199  19.502384     1.581123    middle         low
2006  1.791401  20.362329     1.758329      high         low
2007  1.747671  18.255260     3.392795       low        high
2008  2.061013  19.332541     1.690219    middle         low
2009  2.057332  19.277068     2.606575    middle      middle
2010  1.918029  18.809342     2.114740       low      middle
2011  1.753483  20.708521     1.327918      high         low
2012  2.051470  20.395328     1.978743      high         low
2013  2.031663  19.029507     2.335808       low      middle
2014  2.134060  18.667260     1.827945       low         low
2015  1.922514  19.472274     3.232493    middle        high
2016  2.168768  19.587678     2.845464    middle        high
2017  2.201143  20.189534     2.199041      high      middle
2018  1.850561  19.489836     2.653151    middle      middle
2019  1.974003  19.281123     1.816055    middle         low
2020  2.165068  19.895874     2.388333      high      middle

In [80]:
merged3.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/mergedbyyear_precibins.csv")

In [61]:
merged3.head()

Empty DataFrame
Columns: [Date, DayOfYear, QA, RelativeAzimuth, SolarZenith, StateQA, ViewZenith, p, sur_refl_b01, sur_refl_b02, sur_refl_b03, sur_refl_b04, sur_refl_b05, sur_refl_b06, sur_refl_b07, DayOfYear_p10, DayOfYear_p50, DayOfYear_p90, QA_p10, QA_p50, QA_p90, RelativeAzimuth_p10, RelativeAzimuth_p50, RelativeAzimuth_p90, SolarZenith_p10, SolarZenith_p50, SolarZenith_p90, StateQA_p10, StateQA_p50, StateQA_p90, ViewZenith_p10, ViewZenith_p50, ViewZenith_p90, p_p10, p_p50, p_p90, sur_refl_b01_p10, sur_refl_b01_p50, sur_refl_b01_p90, sur_refl_b02_p10, sur_refl_b02_p50, sur_refl_b02_p90, sur_refl_b03_p10, sur_refl_b03_p50, sur_refl_b03_p90, sur_refl_b04_p10, sur_refl_b04_p50, sur_refl_b04_p90, sur_refl_b05_p10, sur_refl_b05_p50, sur_refl_b05_p90, sur_refl_b06_p10, sur_refl_b06_p50, sur_refl_b06_p90, sur_refl_b07_p10, sur_refl_b07_p50, sur_refl_b07_p90, DayOfYear.1, QA.1, RelativeAzimuth.1, SolarZenith.1, StateQA.1, ViewZenith.1, p.1, sur_refl_b01.1, sur_refl_b02.1, sur_refl_b03.1, sur_refl_b04.1, sur_refl_b05.1, sur_refl_b06.1, sur_refl_b07.1, DayOfYear.2, QA.2, RelativeAzimuth.2, SolarZenith.2, StateQA.2, ViewZenith.2, p.2, sur_refl_b01.2, sur_refl_b02.2, sur_refl_b03.2, sur_refl_b04.2, sur_refl_b05.2, sur_refl_b06.2, sur_refl_b07.2, clouds_cover, latlong, T2M, PRECTOTCORR]
Index: []

[0 rows x 89 columns]

In [80]:
def season1(month):
    if month==12 or month==1 or month==2:
        return "winter"   
    elif month==3 or month==4 or month==5 :
        return "spring"
    elif month==6 or month==7 or month==8:
        return "summer"
    else:
        return "fall"

In [60]:
season_copy=new_climatedata_copy.copy()

In [61]:
def getMonths(input, m1, m2, m3):
    return input.loc[(input.date.dt.month==m1) | (input.date.dt.month==m2) | (input.date.dt.month==m3)]

In [62]:
Spring = getMonths(season_copy,3,4,5)

AttributeError: 'DataFrame' object has no attribute 'date'

In [63]:
season_copy

      YEAR  MO  DY    T2M  PRECTOTCORR       Date
0     2000   1   1  14.27         0.00 2000-01-01
1     2000   1   2  17.54         0.01 2000-01-02
2     2000   1   3  12.62         0.00 2000-01-03
3     2000   1   4   3.95         0.00 2000-01-04
4     2000   1   5   4.19         0.00 2000-01-05
...    ...  ..  ..    ...          ...        ...
8031  2021  12  27  19.58         0.59 2021-12-27
8032  2021  12  28  19.93         0.91 2021-12-28
8033  2021  12  29  18.08         3.09 2021-12-29
8034  2021  12  30  15.46         0.00 2021-12-30
8035  2021  12  31  19.43         1.21 2021-12-31

[8036 rows x 6 columns]

In [81]:
season_list = []

for month in season_copy['MO']:
    season = season1(month)
    season_list.append(season)
    
season_copy['Season_list'] = season_list

In [82]:
season_copy.head()

   YEAR  MO  DY    T2M  PRECTOTCORR       Date Season_list
0  2000   1   1  14.27         0.00 2000-01-01      winter
1  2000   1   2  17.54         0.01 2000-01-02      winter
2  2000   1   3  12.62         0.00 2000-01-03      winter
3  2000   1   4   3.95         0.00 2000-01-04      winter
4  2000   1   5   4.19         0.00 2000-01-05      winter

In [83]:
new_dataframe_season=season_copy.groupby(['YEAR', 'Season_list'])[['T2M','PRECTOTCORR'  ]].mean()

In [84]:
new_dataframe_season.head()

                        T2M  PRECTOTCORR
YEAR Season_list
2000 fall         19.243736     3.664066
     spring       20.404348     2.409565
     summer       30.267717     1.755217
     winter        9.337033     1.797692
2001 fall         19.140769     2.738681

In [68]:
new_dataframe_season.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/mergedbyseason1.csv")

NameError: name 'new_dataframe_season' is not defined

In [85]:
new_dataframe_season.head()

                        T2M  PRECTOTCORR
YEAR Season_list
2000 fall         19.243736     3.664066
     spring       20.404348     2.409565
     summer       30.267717     1.755217
     winter        9.337033     1.797692
2001 fall         19.140769     2.738681

In [86]:
merged4=pd.merge(twoBDAdata, season_copy, left_on='Date', right_on='Date')

In [87]:
merged4

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,YEAR,MO,DY,T2M,PRECTOTCORR,Season_list
0,2000-06-01,156.060606,1.073742e+09,-1737.454545,1934.121212,1049.515152,3904.969697,1.272331,2956.636364,3717.575758,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,1,28.20,0.50,summer
1,2000-06-09,164.030303,1.074687e+09,-1381.090909,1922.272727,1293.121212,4098.393939,1.502990,1488.757576,2277.818182,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,9,24.10,12.00,summer
2,2000-06-17,173.484848,1.073742e+09,7163.060606,1662.666667,4516.424242,4540.636364,2.022717,945.121212,1913.727273,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,17,26.34,13.11,summer
3,2000-06-25,177.000000,1.350312e+09,-1762.727273,1605.515152,4519.272727,982.636364,2.703099,960.060606,2698.757576,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,25,29.08,0.07,summer
4,2000-07-03,186.000000,1.090011e+09,-1521.181818,1786.515152,80.000000,2157.151515,2.881762,816.242424,2348.000000,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,7,3,30.57,0.09,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,2020-06-25,184.000000,1.073742e+09,-1277.000000,1954.515152,4065.818182,1163.636364,3.066000,606.454545,1853.424242,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,6,25,25.80,0.06,summer
923,2020-07-03,185.000000,1.073742e+09,14984.242420,1188.000000,88.000000,5614.000000,1.966876,749.303030,1477.727273,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,3,29.73,0.02,summer
924,2020-07-11,193.000000,1.074759e+09,-1153.212121,2153.515152,115.151515,2349.151515,3.929599,706.424242,2831.030303,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,11,31.33,0.00,summer
925,2020-07-19,201.484848,1.074759e+09,6822.121212,1865.181818,4734.666667,4527.151515,3.388338,764.969697,2647.939394,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,19,31.24,0.03,summer
926,2020-07-27,214.000000,1.073742e+09,15303.909090,2081.515152,4519.515152,1384.363636,2.695053,770.545455,2071.939394,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,27,29.17,2.65,summer

In [91]:
new_dataframe_season=merged4.groupby('Season_list['spring'])[['T2M','PRECTOTCORR','p'  ]].mean()

SyntaxError: invalid syntax (<ipython-input-91-9f82bb1e09f9>, line 1)

In [126]:
is_spring=merged4['Season_list']=='spring' and merged4['Season_list']=='summer'

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [99]:
new_dataframe_season_spring= merged4[is_spring]

In [100]:
new_dataframe_season_spring

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,YEAR,MO,DY,T2M,PRECTOTCORR,Season_list
35,2001-03-06,71.0,1.073742e+09,-4541.575758,4180.030303,80.000000,4939.151515,1.349420,893.666667,1213.515152,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,6,11.54,0.01,spring
36,2001-03-14,74.0,1.073742e+09,11981.606060,3704.515152,84.121212,202.393939,1.606810,879.606061,1421.515152,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,14,14.26,6.29,spring
37,2001-03-22,81.0,1.073742e+09,12752.000000,3368.515152,88.000000,1502.363636,1.588641,962.090909,1514.090909,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,22,16.18,0.17,spring
38,2001-03-30,90.0,1.073742e+09,13063.393940,3086.515152,4302.303030,254.363636,1.913456,801.181818,1536.151515,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,30,12.15,1.06,spring
39,2001-04-07,99.0,1.073742e+09,-4241.757576,2832.030303,1048.515152,1038.151515,1.518576,2378.181818,3181.484848,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,4,7,22.19,0.13,spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,2020-04-22,120.0,1.074759e+09,-2946.333333,2352.515152,83.878788,1120.151515,2.690200,764.181818,2178.000000,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,4,22,21.43,2.36,spring
915,2020-04-30,122.0,1.073742e+09,-2739.272727,2510.515152,88.000000,3364.000000,2.040712,602.363636,1211.060606,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,4,30,20.51,0.00,spring
916,2020-05-08,131.0,1.523168e+09,-2180.000000,2445.000000,152.000000,4241.000000,2.893318,567.636364,1800.454545,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,8,22.16,0.02,spring
917,2020-05-16,139.0,1.073742e+09,14284.242420,1493.000000,88.000000,4381.000000,2.960954,440.666667,1283.757576,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,16,21.06,10.34,spring
918,2020-05-24,150.0,1.073742e+09,15764.393940,1660.515152,1044.121212,1402.363636,1.952492,1394.090909,2703.545455,...,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,24,24.45,19.66,spring

In [101]:
new_dataframe_season_spring['Temp_bins']=pd.cut(new_dataframe_season_spring['T2M'], bins=3, labels=('low', 'middle', 'high'))

<ipython-input-101-6130856ef79e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe_season_spring['Temp_bins']=pd.cut(new_dataframe_season_spring['T2M'], bins=3, labels=('low', 'middle', 'high'))

In [102]:
new_dataframe_season_spring

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b07.2,clouds_cover,latlong,YEAR,MO,DY,T2M,PRECTOTCORR,Season_list,Temp_bins
35,2001-03-06,71.0,1.073742e+09,-4541.575758,4180.030303,80.000000,4939.151515,1.349420,893.666667,1213.515152,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,6,11.54,0.01,spring,low
36,2001-03-14,74.0,1.073742e+09,11981.606060,3704.515152,84.121212,202.393939,1.606810,879.606061,1421.515152,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,14,14.26,6.29,spring,middle
37,2001-03-22,81.0,1.073742e+09,12752.000000,3368.515152,88.000000,1502.363636,1.588641,962.090909,1514.090909,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,22,16.18,0.17,spring,middle
38,2001-03-30,90.0,1.073742e+09,13063.393940,3086.515152,4302.303030,254.363636,1.913456,801.181818,1536.151515,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,30,12.15,1.06,spring,middle
39,2001-04-07,99.0,1.073742e+09,-4241.757576,2832.030303,1048.515152,1038.151515,1.518576,2378.181818,3181.484848,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,4,7,22.19,0.13,spring,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,2020-04-22,120.0,1.074759e+09,-2946.333333,2352.515152,83.878788,1120.151515,2.690200,764.181818,2178.000000,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,4,22,21.43,2.36,spring,high
915,2020-04-30,122.0,1.073742e+09,-2739.272727,2510.515152,88.000000,3364.000000,2.040712,602.363636,1211.060606,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,4,30,20.51,0.00,spring,high
916,2020-05-08,131.0,1.523168e+09,-2180.000000,2445.000000,152.000000,4241.000000,2.893318,567.636364,1800.454545,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,8,22.16,0.02,spring,high
917,2020-05-16,139.0,1.073742e+09,14284.242420,1493.000000,88.000000,4381.000000,2.960954,440.666667,1283.757576,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,16,21.06,10.34,spring,high
918,2020-05-24,150.0,1.073742e+09,15764.393940,1660.515152,1044.121212,1402.363636,1.952492,1394.090909,2703.545455,...,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,24,24.45,19.66,spring,high

In [103]:
new_dataframe_season_spring['preci_bins']=pd.cut(new_dataframe_season_spring['PRECTOTCORR'], bins=3, labels=('low', 'middle', 'high'))

<ipython-input-103-2d83c2933796>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe_season_spring['preci_bins']=pd.cut(new_dataframe_season_spring['PRECTOTCORR'], bins=3, labels=('low', 'middle', 'high'))

In [104]:
new_dataframe_season_spring

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,clouds_cover,latlong,YEAR,MO,DY,T2M,PRECTOTCORR,Season_list,Temp_bins,preci_bins
35,2001-03-06,71.0,1.073742e+09,-4541.575758,4180.030303,80.000000,4939.151515,1.349420,893.666667,1213.515152,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,6,11.54,0.01,spring,low,low
36,2001-03-14,74.0,1.073742e+09,11981.606060,3704.515152,84.121212,202.393939,1.606810,879.606061,1421.515152,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,14,14.26,6.29,spring,middle,low
37,2001-03-22,81.0,1.073742e+09,12752.000000,3368.515152,88.000000,1502.363636,1.588641,962.090909,1514.090909,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,22,16.18,0.17,spring,middle,low
38,2001-03-30,90.0,1.073742e+09,13063.393940,3086.515152,4302.303030,254.363636,1.913456,801.181818,1536.151515,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,30,12.15,1.06,spring,middle,low
39,2001-04-07,99.0,1.073742e+09,-4241.757576,2832.030303,1048.515152,1038.151515,1.518576,2378.181818,3181.484848,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,4,7,22.19,0.13,spring,high,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,2020-04-22,120.0,1.074759e+09,-2946.333333,2352.515152,83.878788,1120.151515,2.690200,764.181818,2178.000000,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,4,22,21.43,2.36,spring,high,low
915,2020-04-30,122.0,1.073742e+09,-2739.272727,2510.515152,88.000000,3364.000000,2.040712,602.363636,1211.060606,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,4,30,20.51,0.00,spring,high,low
916,2020-05-08,131.0,1.523168e+09,-2180.000000,2445.000000,152.000000,4241.000000,2.893318,567.636364,1800.454545,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,8,22.16,0.02,spring,high,low
917,2020-05-16,139.0,1.073742e+09,14284.242420,1493.000000,88.000000,4381.000000,2.960954,440.666667,1283.757576,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,16,21.06,10.34,spring,high,low
918,2020-05-24,150.0,1.073742e+09,15764.393940,1660.515152,1044.121212,1402.363636,1.952492,1394.090909,2703.545455,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,5,24,24.45,19.66,spring,high,middle

In [105]:
new_dataframe_season_spring.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/bins_season_preci_spring.csv")

In [75]:
merged4

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,latlong,YEAR,MO,DY,T2M,PRECTOTCORR
0,2000-06-01,156.060606,1.073742e+09,-1737.454545,1934.121212,1049.515152,3904.969697,1.272331,2956.636364,3717.575758,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,1,28.20,0.50
1,2000-06-09,164.030303,1.074687e+09,-1381.090909,1922.272727,1293.121212,4098.393939,1.502990,1488.757576,2277.818182,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,9,24.10,12.00
2,2000-06-17,173.484848,1.073742e+09,7163.060606,1662.666667,4516.424242,4540.636364,2.022717,945.121212,1913.727273,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,17,26.34,13.11
3,2000-06-25,177.000000,1.350312e+09,-1762.727273,1605.515152,4519.272727,982.636364,2.703099,960.060606,2698.757576,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,6,25,29.08,0.07
4,2000-07-03,186.000000,1.090011e+09,-1521.181818,1786.515152,80.000000,2157.151515,2.881762,816.242424,2348.000000,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2000,7,3,30.57,0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,2020-06-25,184.000000,1.073742e+09,-1277.000000,1954.515152,4065.818182,1163.636364,3.066000,606.454545,1853.424242,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,6,25,25.80,0.06
923,2020-07-03,185.000000,1.073742e+09,14984.242420,1188.000000,88.000000,5614.000000,1.966876,749.303030,1477.727273,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,3,29.73,0.02
924,2020-07-11,193.000000,1.074759e+09,-1153.212121,2153.515152,115.151515,2349.151515,3.929599,706.424242,2831.030303,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,11,31.33,0.00
925,2020-07-19,201.484848,1.074759e+09,6822.121212,1865.181818,4734.666667,4527.151515,3.388338,764.969697,2647.939394,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,19,31.24,0.03
926,2020-07-27,214.000000,1.073742e+09,15303.909090,2081.515152,4519.515152,1384.363636,2.695053,770.545455,2071.939394,...,0,0,0,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2020,7,27,29.17,2.65

In [76]:
import pandas as pd

variables = np.random.randn(1200,3)
time = pd.date_range("2016-01-01", periods=1200, name='date')
df = pd.DataFrame(variables, columns=['f1','f2','f3'], index=time).reset_index()

In [77]:
import numpy as np

In [78]:
df

           date        f1        f2        f3
0    2016-01-01 -1.080015 -0.478906  0.839562
1    2016-01-02 -1.934292  0.573636  0.333678
2    2016-01-03  0.592646 -0.949389  1.006198
3    2016-01-04 -0.729126 -0.733110 -1.130774
4    2016-01-05 -0.478859  0.508654 -0.410160
...         ...       ...       ...       ...
1195 2019-04-10  0.524745  0.406205  1.094995
1196 2019-04-11  0.832546 -0.478955 -0.715687
1197 2019-04-12  1.358397  1.558408  0.394646
1198 2019-04-13  1.474566 -0.670665 -1.670787
1199 2019-04-14 -0.502530  0.852415  1.109195

[1200 rows x 4 columns]

In [39]:
import os
import ee
import geemap
import ipywidgets as widgets
from bqplot import pyplot as plt
from ipyleaflet import WidgetControl
from ipywidgets import HBox, Label, Layout
from IPython.display import display
import datetime 
import time

In [41]:
geemap.ee_initialize()

In [44]:
# Create an interactive map
Map = geemap.Map(center=[31, -100], zoom=9, add_google_map=False, height="1500px")
Map.add_basemap('HYBRID')
Map.add_basemap('ROADMAP')

In [45]:
Map

Map(center=[31, -100], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=HBox(children=(Tâ€¦

In [ ]:
#Sea Surface Temperature

In [46]:
dataset = ee.ImageCollection('MODIS/006/MOD11A1').filter(ee.Filter.date('2018-01-01', '2018-05-01'));
landSurfaceTemperature = dataset.select('LST_Day_1km');
landSurfaceTemperatureVis = {
  min: 13000.0,
  max: 16500.0,
  'palette': [
    '040274', '040281', '0502a3', '0502b8', '0502ce', '0502e6',
    '0602ff', '235cb1', '307ef3', '269db1', '30c8e2', '32d3ef',
    '3be285', '3ff38f', '86e26f', '3ae237', 'b5e22e', 'd6e21f',
    'fff705', 'ffd611', 'ffb613', 'ff8b13', 'ff6e08', 'ff500d',
    'ff0000', 'de0101', 'c21301', 'a71001', '911003'
  ],
};

In [47]:
Map.setCenter(6.746, 46.529, 2);
Map.addLayer(landSurfaceTemperature, landSurfaceTemperatureVis,'Land Surface Temperature');
Map

Map(bottom=428184.96003723145, center=[46.529, 6.746], controls=(WidgetControl(options=['position', 'transpareâ€¦

In [127]:
subsetDataFrame = new_dataframe_season_spring[new_dataframe_season_spring['Season_list'].isin(['spring', 'summer']) ]

In [133]:
subsetDataFrame.head()

,Date,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,...,clouds_cover,latlong,YEAR,MO,DY,T2M,PRECTOTCORR,Season_list,Temp_bins,preci_bins
35,2001-03-06,71.0,1.073742e+09,-4541.575758,4180.030303,80.000000,4939.151515,1.349420,893.666667,1213.515152,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,6,11.54,0.01,spring,low,low
36,2001-03-14,74.0,1.073742e+09,11981.606060,3704.515152,84.121212,202.393939,1.606810,879.606061,1421.515152,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,14,14.26,6.29,spring,middle,low
37,2001-03-22,81.0,1.073742e+09,12752.000000,3368.515152,88.000000,1502.363636,1.588641,962.090909,1514.090909,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,22,16.18,0.17,spring,middle,low
38,2001-03-30,90.0,1.073742e+09,13063.393940,3086.515152,4302.303030,254.363636,1.913456,801.181818,1536.151515,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,3,30,12.15,1.06,spring,middle,low
39,2001-04-07,99.0,1.073742e+09,-4241.757576,2832.030303,1048.515152,1038.151515,1.518576,2378.181818,3181.484848,...,0,"ee.Geometry({\n ""functionInvocationValue"": {\...",2001,4,7,22.19,0.13,spring,high,low

In [130]:
subsetDataFrame.shape

(220, 95)

In [131]:
subsetDataFrame.describe()

,DayOfYear,QA,RelativeAzimuth,SolarZenith,StateQA,ViewZenith,p,sur_refl_b01,sur_refl_b02,sur_refl_b03,...,sur_refl_b04.2,sur_refl_b05.2,sur_refl_b06.2,sur_refl_b07.2,clouds_cover,YEAR,MO,DY,T2M,PRECTOTCORR
count,220.000000,2.200000e+02,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,...,220.0,220.0,220.0,220.0,220.0,220.000000,220.000000,220.000000,220.000000,220.000000
mean,108.516253,1.088610e+09,3890.891184,2770.667493,665.228512,2490.905372,2.078851,935.445455,1785.572176,702.460882,...,0.0,0.0,0.0,0.0,0.0,2010.500000,3.977273,15.795455,19.039545,2.412818
std,25.594163,8.170797e+07,7945.914689,772.859580,1502.360713,1592.095167,0.717737,726.099079,832.420991,765.201401,...,0.0,0.0,0.0,0.0,0.0,5.779431,0.840978,8.620829,5.388618,6.031352
min,65.000000,1.073742e+09,-4688.636364,1095.030303,52.848485,156.363636,0.654874,346.363636,417.151515,221.090909,...,0.0,0.0,0.0,0.0,0.0,2001.000000,3.000000,1.000000,3.590000,0.000000
25%,86.113636,1.073742e+09,-3376.931818,2168.643940,84.121212,1088.000000,1.547805,645.977273,1329.227273,416.515151,...,0.0,0.0,0.0,0.0,0.0,2005.750000,3.000000,7.750000,15.517500,0.000000
50%,109.000000,1.073742e+09,-1591.969697,2703.272727,88.000000,2263.318182,1.967726,756.590909,1649.803030,484.439394,...,0.0,0.0,0.0,0.0,0.0,2010.500000,4.000000,15.000000,19.935000,0.020000
75%,131.393939,1.073742e+09,12985.530305,3457.651515,153.090909,3617.363636,2.604403,921.045455,2105.621212,590.500000,...,0.0,0.0,0.0,0.0,0.0,2015.250000,5.000000,23.000000,22.820000,1.065000
max,152.000000,1.557739e+09,16054.121210,4565.515152,8216.000000,5694.848485,4.255683,7913.484848,7990.333333,7732.545455,...,0.0,0.0,0.0,0.0,0.0,2020.000000,5.000000,30.000000,28.900000,33.430000

In [132]:
subsetDataFrame.to_csv("C:/Users/RITIKA/Downloads/datasets for the analysis/re-analysis/subsetteddataframebysummerandsprinf.csv")